export const GET_DOGS = 'GET_DOGS';
export const GET_DOG = 'GET_DOG';
export const SEARCH_DOG = 'SEARCH_DOG';
export const GET_DETAILS = 'GET_DETAILS';
export const DELETE_DETAILS = 'DELETE_DETAILS';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const POST_DOG = 'POST_DOG';
export const SET_PAGE = "SET_PAGE"
export const SET_TOTAL_PAGE = "SET_TOTAL_PAGE"
export const PAGINATE = 'PAGINATE';
export const FILTER = 'FILTER';
export const FILTERORIGIN= 'FILTERORIGIN';
export const ORDER = 'ORDER';
export const ORDERBYWEIGHT = 'ORDERBYWEIGHT';